export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const FETCH_INGREDIENTS_FAILURE = 'FETCH_INGREDIENTS_FAILURE';
export const FETCH_TOTAL_PRICE_FAILURE = 'FETCH_TOTAL_PRICE_FAILURE';

export const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILURE = 'PURCHASE_BURGER_FAILURE';

export const FETCH_ORDERS = 'FETCH_ORDERS'
export const LOAD_ORDERS = 'LOAD_ORDERS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';